version: "3"

services:
  # mailhog:
  #   image: mailhog/mailhog
  #   ports:
  #     - 1025:1025
  #     - 8025:8025
  postgres:
    image: kartoza/postgis
    ports:
      - 5432:5432
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
  redis:
    image: redis:alpine
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - 6379:6379
      - 6380:6380
  app:
    build: .
    env_file: .env
    # adonis kue:listen and adonis migration:run
    command: "npm start"
    environment:
      # - MAIL_HOST=mailhog
      - PG_HOST=postgres
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/
    ports:
      - 3333:3333
